apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-{{.Release.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: solar-{{.Release.Name}}
    spec:
      containers:
      - name: solar-{{.Release.Name}}
        image: neilpeterson/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: {{ .Values.title }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
  selector:
    app: solar-{{.Release.Name}}